
names = {'autodiff', ...
         'internal', ...
         'multiscale', ...
         'visualization', ...
         'model-io', ...
         'solvers'};
names = cellfun(@(x) fullfile(ROOTDIR, '..', ['mrst-', x]), names, ...
                    'UniformOutput', false);

mrstPath('addroot', names{:});
mrstPath('add', 'co2lab', fullfile(ROOTDIR, '..', 'mrst-co2lab', 'co2lab'));

mrstPath('add', '2RegionsDomain', '/Users/davide/mrst-davide');
mrstModule add 2RegionsDomain
clear namesmrstPath reregister matlab_bgl ...
    '/Users/davide/mrst-bitbucket/checkout-mrst/mrst-bitbucket/mrst-core/utils/3rdparty/matlab_bgl/matlab_bgl'
