%% Plot of different schemes
% here anayticl case, data obtained from List Radu
% Computational times and number of iterations
close all
clear all

%% Mesh size
x = [10 20 40 80];
%% Compare the diffrent schemes  
% example with inital and boundary pressure -2

%Comapre different L (max of derivatives was Theta_p = .15 Theta_c = .008)
% method 1 (monolithic)
% Lp_1 = .2    Lc_1 = .01
t_L_1_1 = [3.717 4.715 8.915 37.788];
n_L_1_1 = [37 39 42 44];

% Lp_2 = .1    Lc_2 = .005   %not working
%t_L_2_1 = [3.2 4.1 7.6 31.5];
%n_L_2_1 = [44 48 51 54];

% Lp_3 = .5    Lc_3 = .1
t_L_3_1 = [9.445 12.842 25.319 114.486];
n_L_3_1 = [107 114 122 129];

% method 2  (calssical approach sequential)
% Lp_1 = .2    Lc_1 = .01
t_L_1_2 = [15.864 20.496 33.762 89.662];
n_L_1_2 = [184 202 222 259];

% Lp_2 = .1    Lc_2 = .005
t_L_2_2 = [10.502 13.291 21.198 55.462];
n_L_2_2 = [115 125 134 152];

% Lp_3 = .5    Lc_3 = .1
t_L_3_2 = [30.898 39.821 67.674 185.915];
n_L_3_2 = [377 411 479 535];

% method 3   (alternative sequental)
% Lp_1 = .2    Lc_1 = .01
t_L_1_3 = [16.775 21.836 36.666 94.481];
n_L_1_3 = [167 185 206 224];

% Lp_2 = .1    Lc_2 = .005
t_L_2_3 = [10.879 13.191 19.477 46.752];
n_L_2_3 = [76 82 88 92];

% Lp_3 = .5    Lc_3 = .1
t_L_3_3 = [65.562 76.517 102.461 203.074];
n_L_3_3 = [296 320 340 358];

%{
figure, grid on, plot(x,t_L_1_1,'--o', x,t_L_3_1,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different L (FIM)'), legend('Lp_1 = .2 Lc_1 = .01', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest');
figure, grid on, plot(x,n_L_1_1,'--o',x,n_L_3_1,'--o'), title('Number of Iterations different L (FIM)'), legend('Lp_1 = .2 Lc_1 = .01', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ; 

figure, grid on, plot(x,n_L_1_1,'--o',x,n_L_3_1,'--o'), title('Number of Iterations different L (FIM)'), legend('Lp_1 = .2 Lc_1 = .01', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ; 

figure, grid on, plot(x,t_L_1_2,'--o',x,t_L_2_2,'--o',x,t_L_3_2,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different L (Sequential)'), legend('Lp_1 = .2 Lc_1 = .01','Lp_1 = .1 Lc_1 = .005', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest');
figure, grid on, plot(x,n_L_1_2,'--o',x,n_L_2_2,'--o',x,n_L_3_2,'--o'), title('Number of Iterations different L (Sequential)'), legend('Lp_1 = .2 Lc_1 = .01','Lp_1 = .1 Lc_1 = .005', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ; 

figure, grid on, plot(x,t_L_1_3,'--o',x,t_L_2_3,'--o',x,t_L_3_3,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different L (Alternative Sequential)'), legend('Lp_1 = .2 Lc_1 = .01','Lp_1 = .1 Lc_1 = .005', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest');
figure, grid on, plot(x,n_L_1_3,'--o',x,n_L_2_3,'--o',x,n_L_3_3,'--o'), title('Number of Iterations different L (Alternative Sequential)'), legend('Lp_1 = .2 Lc_1 = .01','Lp_1 = .1 Lc_1 = .005', 'Lp_1 = .5 Lc_1 = .1','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ; 
%}

% Newton
t_N_1 = [1.157 1.278 1.837 4.904];
n_N_1 = [4 4 4 4];

t_N_2 = [1.718 1.976 2.838 6.360];
n_N_2 = [9 13 14 14];
n_N_ext_2 = [2 3 3 3];

t_N_3 = [2.269 2.599 3.401 7.319];
n_N_3 = [11 11 13 13];
n_N_ext_3 = [5 5 6 6];

% Picard
t_P_1 = [1.04 1.139 1.577 4.281];
n_P_1 = [4 4 4 4];

t_P_2 = [1.811 1.962 2.7637 8.666];
n_P_2 = [10 14 15 20];
n_P_ext_2 = [2 3 3 4];

t_P_3 = [2.942 3.342 4.534 10.287];
n_P_3 = [13 13 13 15];
n_P_ext_3 = [6 6 6 7];
%{
figure, grid on, plot(x,t_L_1_1,'--o',x,t_N_1,'--*',x,t_P_1,'--o'), title('Computational Times different Schemes (FIM)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Time (s)');
figure, grid on, plot(x,n_L_1_1,'--o',x,n_N_1,'--*',x,n_P_1,'--o'), title('Number of Iterations different Schemes (FIM)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ;

figure, grid on, plot(x,t_L_2_2,'--o',x,t_N_2,'--*',x,t_P_2,'--o'), title('Computational Times different Schemes (Sequential)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Time (s)');
figure, plot(x,n_L_2_2,'--o',x,n_N_2,'--*',x,n_P_2,'--o'), title('Number of Iterations different Schemes (Sequential)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ;

figure, grid on, plot(x,t_L_1_3,'--o',x,t_N_3,'--*',x,t_P_3,'--o'), title('Computational Times different Schemes (Alternative Sequential)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Time (s)');
figure, grid on, plot(x,n_L_1_3,'--o',x,n_N_3,'--*',x,n_P_3,'--o'), title('Number of Iterations different Schemes (Alternative Sequential)'), legend('L Scheme', 'Newton Method', 'Modified Picard','Location','NorthWest'), xlabel('1/h'), ylabel('Iterations') ;
%}
figure, grid on, plot(x,t_L_1_1,'--o', x,t_L_3_1,'--o', x,t_L_1_2,'--o', x,t_L_2_2,'--o',x,t_L_3_2,'--o', x,t_L_1_3,'--o', x,t_L_2_3,'--o',x,t_L_3_3,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different L Schemes'), legend('Lp_1 = .2 Lc_1 = .01 (FIM)', 'Lp_3 = .5 Lc_3 = .1 (FIM)',...
    'Lp_1 = .2 Lc_1 = .01 (Sequential)', 'Lp_2 = .1 Lc_2 = .005 (Sequential)', 'Lp_3 = .5 Lc_3 = .1 (Sequential)', ...
    'Lp_1 = .2 Lc_1 = .01 (Alternative Seq)', 'Lp_2 = .1 Lc_2 = .005 (Alternative Seq)', 'Lp_3 = .5 Lc_3 = .1 (Alternative Seq)', ...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'YTick',-1.5:.5:1.5,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')


figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot(x,n_L_1_1,'--o', x,n_L_3_1,'--o', x,n_L_1_2,'--+', x,n_L_2_2,'--+',x,n_L_3_2,'--+', x,n_L_1_3,'--*', x,n_L_2_3,'--*',x,n_L_3_3,'--*'),...
    xlabel('1/h', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times'), ylabel('Number Iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times') , legend('Lp_1 = .2 Lc_1 = .01 (FIM)', 'Lp_3 = .5 Lc_3 = .1 (FIM)',...
    'Lp_1 = .2 Lc_1 = .01 (Sequential)', 'Lp_2 = .2 Lc_2 = .005 (Sequential)', 'Lp_3 = .5 Lc_3 = .1 (Sequential)', ...
    'Lp_1 = .2 Lc_1 = .01 (Alternative Seq)', 'Lp_2 = .1 Lc_2 = .005 (Alternative Seq)', 'Lp_3 = .5 Lc_3 = .1 (Alternative Seq)', ...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')
 print -depsc2 iterationsDifferentL.eps



figure, grid on, plot(x,t_L_1_1,'--o', x,t_N_1,'--o', x,t_P_1,'--o',...
    x,t_L_2_2,'--+',x,t_N_2,'--+', x,t_P_2,'--+',...
    x,t_L_2_3,'--o',x,t_N_3,'--o', x,t_P_3,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different Schemes and Approaches'),...
    legend('Lp_1 = .2 Lc_1 = .01 (FIM)', 'Newton (FIM)', 'Picard (FIM)',...
    'Lp_2 = .1 Lc_2 = .005 (Sequential)', 'Newton (Sequential)', 'Picard (Sequential)',...
    'Lp_2 = .1 Lc_2 = .005 (Alternative Seq)', 'Newton (Alternative Seq)', 'Picard (Alternative Seq)',...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'YTick',-1.5:.5:1.5,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')


figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot(x,n_L_1_1,'--o', x,n_N_1,'--o', x,n_P_1,'--o',...
    x,n_L_2_2,'--+',x,n_N_2,'--+', x,n_P_2,'--+',...
    x,n_L_2_3,'--*',x,n_N_3,'--*', x,n_P_3,'--*'),...
    xlabel('1/h', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times'), ylabel('Number Iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times') ,...
    legend({'Lp_1 = .2 Lc_1 = .01 (FIM)', 'Newton (FIM)', 'Picard (FIM)',...
    'Lp_2 = .1 Lc_2 = .005 (Sequential)', 'Newton (Sequential)', 'Picard (Sequential)',...
    'Lp_2 = .1 Lc_2 = .005 (Alternative Seq)', 'Newton (Alternative Seq)', 'Picard (Alternative Seq)'},...
      'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times',...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')
 print -depsc2 iterationsdifferentschemes.eps




figure, grid on, plot( x,t_N_1,'--o', x,t_P_1,'--o',...
    x,t_N_2,'--o', x,t_P_2,'--o',...
   x,t_N_3,'--o', x,t_P_3,'--o'), xlabel('1/h'), ylabel('Time (s)') , title('Computational Times different Schemes and Approaches'),...
    legend( 'Newton (FIM)', 'Picard (FIM)',...
     'Newton (Sequential)', 'Picard (Sequential)',...
    'Newton (Alternative Seq)', 'Picard (Alternative Seq)',...
    'Location','NorthWest');
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')


figure('Units','inches',...
'PaperPositionMode','auto');
grid on, plot(     x,n_N_2,'--+', x,n_P_2,'--+',...
    x,n_N_3,'--*', x,n_P_3,'--*'),...
    xlabel('1/h', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times'), ylabel('Number Iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times') ,...
    legend( {     'Newton (Sequential)', 'Picard (Sequential)',...
     'Newton (Alternative Seq)', 'Picard (Alternative Seq)'},...
      'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times',...
    'Location','NorthWest'), axis([10 80 3 21]);
set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')
 print -depsc2 iterationsPicardNewton.eps


figure('Units','inches',...
'PaperPositionMode','auto');
 grid on, plot( x,n_N_ext_2,'--*', x,n_N_ext_3,'-.+',...
    x,n_P_ext_2,'--o', x,n_P_ext_3,'-.+'),...
xlabel('1/h', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times'), ylabel('Number of iterations', 'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times') ,...
    legend( {'Newton (Sequential)','Newton (Alternative Seq)',...
     'Picard (Sequential)', 'Picard (Alternative Seq)'},...
      'FontUnits','points',...
'interpreter','latex',...
'FontSize',11,...
'FontName','Times',...
     'Location','SouthEast');

set(gca,...
'Units','normalized',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',12,...
'FontName','Times')
 print -depsc2 externaliterationsPicardNewton.eps
